version: '3.8'
services:
  nginx:
    image: nginx:1.10.2
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/archive/:/etc/nginx/ssl
    links:
      - web
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
    command: /bin/bash -c "nginx -g 'daemon off;'"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env
  redis:
    image: "redis:alpine"
  worker:
    build:
      context: "."
    command: python manage.py celery_worker
    depends_on:
      - web
      - redis
  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
    ports:
      - 5555:5555
    depends_on:
      - worker