# Generated by Django 3.1.6 on 2021-02-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theralogs', '0001_squashed_0016_auto_20210204_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlsession',
            name='recording_length',
            field=models.FloatField(),
        ),
    ]
