# Generated by Django 3.1.4 on 2020-12-21 20:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('theralogs', '0002_auto_20201221_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 21, 20, 56, 37, 451958, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 21, 20, 56, 37, 451958, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tlsession',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 21, 20, 56, 37, 455421, tzinfo=utc)),
        ),
    ]
