# Generated by Django 3.1.6 on 2021-02-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theralogs", "0002_auto_20210210_2026"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tlsession",
            name="recording_json",
        ),
        migrations.AddField(
            model_name="tlsession",
            name="transcript_id",
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
