# Generated by Django 3.1.4 on 2020-12-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theralogs', '0003_auto_20201221_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tlsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
