# Generated by Django 3.1.6 on 2021-02-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theralogs", "0004_auto_20210216_1835"),
    ]

    operations = [
        migrations.AddField(
            model_name="tlsession",
            name="stripe_refund_id",
            field=models.CharField(
                blank=True, editable=False, max_length=200, null=True
            ),
        ),
    ]
