# Generated by Django 3.1.4 on 2020-12-22 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theralogs', '0004_auto_20201221_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tlfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
