# Generated by Django 3.1.6 on 2021-02-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theralogs", "0005_tlsession_stripe_refund_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tlsession",
            name="refunded",
            field=models.BooleanField(default=False),
        ),
    ]
