# Generated by Django 3.1.4 on 2021-01-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theralogs', '0006_auto_20210103_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlsession',
            name='recording_json',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
