# Generated by Django 3.1.6 on 2021-03-15 13:30

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ("theralogs", "0007_tlsession_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapist",
            name="license_id",
            field=django_cryptography.fields.encrypt(
                models.CharField(blank=True, max_length=200, null=True)
            ),
        ),
    ]
