# Generated by Django 3.1.4 on 2021-01-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theralogs', '0007_auto_20210103_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='license_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='state',
            field=models.CharField(max_length=200),
        ),
    ]
