# Generated by Django 3.1.4 on 2021-01-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theralogs', '0008_auto_20210111_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='stripe_customer_id',
            field=models.CharField(default='', editable=False, max_length=200),
            preserve_default=False,
        ),
    ]
