# Generated by Django 3.1.4 on 2021-01-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theralogs', '0009_therapist_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
