# Generated by Django 3.1.4 on 2021-01-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theralogs', '0010_therapist_stripe_payment_method_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlsession',
            name='recording_length',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tlsession',
            name='recording_json',
            field=models.JSONField(editable=False),
        ),
    ]
