# Generated by Django 3.1.4 on 2021-01-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theralogs', '0011_auto_20210113_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlsession',
            name='recording_json',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
