# Generated by Django 3.1.4 on 2021-02-01 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theralogs", "0012_auto_20210113_2146"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TLFile",
        ),
    ]
