# Generated by Django 3.1.4 on 2021-02-01 12:53

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ("theralogs", "0013_delete_tlfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=django_cryptography.fields.encrypt(models.EmailField(max_length=254)),
        ),
        migrations.AlterField(
            model_name="patient",
            name="name",
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200)),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="city",
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200)),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="license_id",
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200)),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="name",
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200)),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="state",
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200)),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="stripe_customer_id",
            field=django_cryptography.fields.encrypt(
                models.CharField(editable=False, max_length=200)
            ),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="stripe_payment_method_id",
            field=django_cryptography.fields.encrypt(
                models.CharField(blank=True, editable=False, max_length=200, null=True)
            ),
        ),
        migrations.RemoveField(
            model_name="tlsession",
            name="recording_json",
        ),
        migrations.AddField(
            model_name="tlsession",
            name="recording_json",
            field=django_cryptography.fields.encrypt(
                models.JSONField(blank=True, editable=False, null=True)
            ),
        ),
    ]
