# Generated by Django 3.1.4 on 2021-02-01 13:55

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ("theralogs", "0014_auto_20210201_1253"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tlsession",
            name="recording_json",
            field=django_cryptography.fields.encrypt(
                models.TextField(blank=True, editable=False, null=True)
            ),
        ),
    ]
