# Generated by Django 3.1.6 on 2021-02-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theralogs", "0015_auto_20210201_1355"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="patient",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="city",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="license_id",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="state",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="stripe_customer_id",
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="stripe_payment_method_id",
            field=models.CharField(
                blank=True, editable=False, max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tlsession",
            name="recording_json",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
